# 异常处理


## try-catch-finally


#### finally
- 只要不是程序突然崩溃，`finally` 内的语句都会被执行。
- 当 `try` 或 `catch` 中有 return 语句时，`finally` 语句将在方法返回之前被执行。
- 当 `finally` 中都有 return 语句时，无论 `try` 或 `catch` 有没有 return 语句，`finally` 语句的返回值都会覆盖原始的返回值。


## try-with-resources

Java 7 中新加入的一种异常处理机制，可以很容易地关闭在 `try-catch` 语句块中使用的资源。

### 使用
> 1. 只有实现了 `java.lang.AutoCloseable` 接口的类的实例才能够通过 `try-with-resources` 语法关闭资源。
> 2. 在使用 `try-with-resource` 的过程中，一定需要了解资源的 `close()` 方法内部的实现逻辑。否则还是可能会导致资源泄露。 

- `try` 中声明的资源对象隐式声明为 `final`；
- 可以通过逗号分隔声明管理多个资源。

### 在资源处理上的对比

#### 1. try-catch-finally
在没有 `try-with-resources` 语法前，一般都需要在 `finally` 语句块中显示关闭资源。

```java
public void test() throws IOException {
    InputStream in = null;
    try {
        in = new FileInputStream("input.log");
        System.out.println(in.read());
    } finally {
        if (in != null) {
            in.close();
        }
    }
}
```
这种方式的缺点，
- 这些资源都需要手动关闭，否则随着程序运行，资源泄露会造成问题。
- 使用资源越多，`finally` 部分的关闭代码也越冗长，而且与业务逻辑无关。

#### 2. try-with-resources
使用 `try-with-resources` 语法，将资源创建语句写到 `try` 后，在 `try` 语句块执行完之后，其中的资源都会被自动关闭。

```java
public void test() throws IOException {
    try(InputStream in = new FileInputStream("input.log")) {
        System.out.println(in.read());
    }
}
```

#### 异常屏蔽
如上述 `try-catch-finally` 示例中，如果 `try` 语句块的 `read()` 方法和 `finally` 语句块的 `close()` 方法都发生 `IOException`，最后抛出的是 `finally` 语句块中的 `IOException` 而 `try` 语句块中的异常被屏蔽了。也就是逻辑代码执行时的发生异常被资源关闭时发生的异常屏蔽了。

而对于开发者来说，往往更关注 `try` 语句块内发生的异常，异常屏蔽会导致开发者难以定位问题。使用 `try-with-resources` 语法就不会这样，甚至会将 `finally` 语句块发生的异常附加到 `try` 语句块抛出的异常之中。